# Configuración del Broker Artemis (nva)
artemis.brokerUrl=tcp://localhost:61616
artemis.username=nicolas
artemis.password=nv123

# Canales de Entrada (Queues)
queue.web=nva_web_pedidos
queue.mkp=nva_mkp_pedidos

# Canal de Salida (Topic)
topic.pedidos=nva_pedidos