# Configuración Artemis
artemis.brokerUrl=tcp://localhost:61616
artemis.username=nicolas
artemis.password=nv123

# Canal de Entrada (Topic)
topic.pedidos=nva_pedidos
subscription.name=nva_pedidos.facturacion

# Endpoint del Servicio SOAP de Facturación
facturacion.soapUrl=http://localhost:8092/ws/facturacion?wsdl