marketplace.baseUrl=http://localhost:8091
marketplace.ordersTodayPath=/orders/today

artemis.brokerUrl=tcp://localhost:61616
artemis.username=nicolas
artemis.password=nv123

queue.nva_mkp_pedidos=nva_mkp_pedidos