# Configuración Artemis
artemis.brokerUrl=tcp://localhost:61616
artemis.username=nicolas
artemis.password=nv123

# Canal de Entrada (Topic)
topic.pedidos=nva_pedidos
subscription.name=nva_pedidos.bodega

# Endpoint del Sistema de Bodega (Simulado REST)
bodega.restUrl=http://localhost:8093/api/despacho