spring.application.name=tiendaweb
spring.web.locale=es_CL
spring.web.locale-resolver=fixed
server.port=8092

# Configuración del Broker Artemis (nva)
artemis.broker-url=tcp://localhost:61616
artemis.user=nicolas
artemis.password=nv123
artemis.queue-web=nva_web_pedidos